<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreatePurchasesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('purchases', function (Blueprint $table) {
            $table->increments('id');
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('drawn_at')->nullable();
            $table->unsignedInteger('user_id')->nullable();
            $table->unsignedInteger('box_id')->nullable();
            $table->unsignedInteger('payment_type')->nullable()->default(0);
            $table->string('payment_token', 256)->nullable();
            $table->unsignedInteger('status')->nullable()->default(0);
            $table->unsignedInteger('content_id')->nullable();
            $table->string('register_token', 100)->nullable();

            $table->dateTime('played_at')->nullable();
            $table->integer('score')->nullable();
            $table->unsignedInteger('reciever_id')->nullable();

            $table->integer('list_price')->default(0);

            $table->index('user_id', 'fk__purchases__user_id_idx');
            $table->index('box_id', 'fk__purchases__box_id_idx');
            $table->index('content_id', 'fk__purchases__content_id_idx');

            $table->index('register_token', 'purchases__register_token_idx');

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::disableForeignKeyConstraints();
        Schema::dropIfExists('purchases');
        Schema::enableForeignKeyConstraints();
    }
}
