<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateUsersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('users', function (Blueprint $table) {
            $table->increments('id');
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->string('name', 256)->nullable();
            $table->string('email', 100)->nullable();
            $table->string('password', 256)->nullable();

            $table->dateTime('birthday')->nullable();
            $table->string('tel', 100)->nullable();
            $table->unsignedInteger('gender')->default(0);

            $table->string('remember_token', 256)->nullable();
            $table->string('init_token', 256)->nullable();
            $table->string('payment_token', 256)->nullable();

            $table->index('email', 'users__email__idx');

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::disableForeignKeyConstraints();
        Schema::dropIfExists('users');
        Schema::enableForeignKeyConstraints();
    }
}
