<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreatePromotionCodesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('promotion_codes', function (Blueprint $table) {
            $table->increments('id');
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->string('campaign', 256)->nullable();
            $table->string('code', 100)->nullable();
            $table->unsignedInteger('price')->default(0);
            $table->unsignedInteger('user_id')->nullable();
            $table->unsignedInteger('purchase_id')->nullable();
            $table->unsignedInteger('box_id')->nullable();

            $table->index('user_id', 'fk__promotion_codes__user_id_idx');
            $table->index('box_id', 'fk__promotion_codes__box_id_idx');
            $table->index('purchase_id', 'fk__promotion_codes__purchase_id_idx');

            $table->index('code', 'promotion_codes__code_idx');
        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::disableForeignKeyConstraints();
        Schema::dropIfExists('promotion_codes');
        Schema::enableForeignKeyConstraints();
    }
}
