<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateContentsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('contents', function (Blueprint $table) {
            $table->increments('id');
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->unsignedInteger('box_id')->nullable();
            
            $table->string('name', 256)->nullable();
            $table->string('number', 256)->nullable();
            $table->mediumText('description')->nullable();
            $table->mediumText('reserve_way')->nullable();

            $table->string('address', 256)->nullable();
            $table->mediumText('access', 256)->nullable();
            $table->string('length', 256)->nullable();
            $table->string('tools', 256)->nullable();
            $table->string('tel', 256)->nullable();
            $table->string('link_url', 256)->nullable();

            $table->mediumText('summary')->nullable();
            $table->string('email', 256)->nullable();

            $table->unsignedInteger('display_priority')->nullable()->default(1);
            $table->unsignedInteger('price')->nullable()->default(0);
            $table->unsignedInteger('reserve_type')->nullable()->default(0);
            $table->unsignedInteger('win_rate')->nullable()->default(1);
            $table->unsignedInteger('content_category_id')->nullable();
            $table->unsignedInteger('provider_id')->nullable();

            $table->index('box_id', 'fk__contents__box_id_idx');
            $table->index('content_category_id', 'fk__contents__content_category_id_idx');
            $table->index('provider_id', 'fk__contents__provider_id_idx');

            $table->index(['box_id', 'display_priority'], 'contents__box_id__display_priority_idx');
        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::disableForeignKeyConstraints();
        Schema::dropIfExists('contents');
        Schema::enableForeignKeyConstraints();
    }
}
