<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateContentImagesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('content_images', function (Blueprint $table) {
            $table->increments('id');
            $table->string('image_url', 256)->nullable();
            $table->unsignedInteger('content_id')->nullable();
            $table->unsignedInteger('priority')->nullable()->default(0);

            $table->index('content_id', 'fk__content_images__content_id_idx');

            $table->index('priority', 'attraction_images__priority__idx');
        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::disableForeignKeyConstraints();
        Schema::dropIfExists('content_images');
        Schema::enableForeignKeyConstraints();
    }
}
